- data/books.json
I've added some of my favourite quotes from my favourite books I've read.
> added quotes from my favourite books

- data/books.json
> updated books.js

- data/movies.json
I have added one movie object in movies.json
> added movies data

- data/tv.json
Kindly review and comment.
Issue #1
> Added 25 quotes from the TV series F.R.I.E.N.D.S

- data/books.json
https://github.com/Snipey/popular-quotes/issues/5
> A Tale of Two Cities quote

- data/anime.json
- data/books.json
anime list added-> naruto shippuden and death note
book list added-> hunger games and maze runner
> lakshay thakur

- data/books.json
> Add book quotes #5 

- data/speeches.json
Hey @Snipey. I've added speech quotes on my forked repo. Please check. Thank you.
> added speeches quotes

- data/books.json
Added a popular quote by a fmous author.
> Added a book quote

- data/anime.json
As requested, I added a anime.
> Added an anime

- data/books.json
-also some minor formatting fixes in books.json
> Added book quote from LOTR

- data/books.json
> Added a book

- data/lyrics.json
- index.js
- types/lyrics.js
Added lyrics quotes to the package.
Closes #62
> Added lyrics quotes feature

- data/movies.json
> Added quote and also formatted the json for data/movies.json

- data/tv.json
Added a new quote from the Billions TV show.
> Added new quote

- data/speeches.json
> added to speech

- data/books.json
> New Books Quotes Added

- data/speeches.json
https://github.com/Snipey/popular-quotes/issues/3
> Luther King speech

- data/movies.json
> Added one more movie quotes

- index.js
Issue #80 
**Description**
On runtime requirements, JSON files will be loaded into memory.
**Motivation and Context**
Step by step refactoring the application for better performance and maintenance.
> On-demand Quote Loading

- .gitignore
- __tests__/sports/unit.test.js
- __tests__/sports/valid.test.js
- data/sports.json
- index.js
Issue #98 
Sports quotes were added to JSON but not in the index.js.
sports.json is added to index.js and all the test has been written
> Sports quote Added to JSON

- data/tv.json
A Mr. robot quote is totally missing....
> adding mr robot quote

- data/movies.json
#2 
Adding a couple new movie quotes!
> Some quotes from Paul Blart and Air Bud

- data/movies.json
> one movie quote added

- data/tv.json
> just added a tv quote

- data/poem.json
- index.js
Added poem quotes to the package.
> adding poem quotes
